### ISSUE TITLE
Design rework of the settings app

### ISSUE THREAD

**Issue by KaffeDiem** [KaffeDiem/dIM#23]
I would love for the settings page to be more aligned with the settings app of iOS.

Currently the `SettingsView` is divided into groups with `GroupBox`. I would like this to be done using `Form` instead.
Tapping a setting should present a detailed view of what said setting does and a toggle to turn it on/off if there is any already. 

1. and 2. on below pictures could be combined into an `About` section just like 3., the other settings should look like 4.

![IMG_3335](https://user-images.githubusercontent.com/44622621/193860736-6e301a52-8294-4e36-b2d1-629ce8fb1566.jpeg)
![IMG_3336](https://user-images.githubusercontent.com/44622621/193861743-14e08786-8d00-4d0a-a3d2-9a350b719e97.jpeg)

**Comment by Terabyte1385** [comment]
I'm working on this. I'll send you some screenshots soon and eventually make a pull request.

**Comment by Terabyte1385** [comment]
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-13 at 21 14 25](https://user-images.githubusercontent.com/78782971/212400596-2e55393b-7e1d-48eb-951a-175befbb430c.png)
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-13 at 21 14 37](https://user-images.githubusercontent.com/78782971/212400600-8265e21a-7723-4a55-a747-9a9768692318.png)
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-13 at 21 14 41](https://user-images.githubusercontent.com/78782971/212400604-674bef2e-384f-43a3-a00d-b8c0e0b23cae.png)
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-13 at 21 14 49](https://user-images.githubusercontent.com/78782971/212400607-dc8658c9-0a96-4857-93bb-be9eb55c841c.png)
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-13 at 21 15 11](https://user-images.githubusercontent.com/78782971/212400608-b179acaf-bf51-4cc9-9291-063e209efa8b.png)
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-13 at 21 15 41](https://user-images.githubusercontent.com/78782971/212400611-a3b12de3-1be7-4113-874b-d3fe3b238f5e.png)

So I tried to make this look as natural and close to iOS's Settings app. Also added the ability to revert username changes. Does it look okay? If yes I'll make a pull request.

**Comment by KaffeDiem** [comment]
It looks absolutely amazing. I am making a few changes to the code on [this branch](https://github.com/KaffeDiem/dIM/tree/feature/settings_overhaul) removing comments and so on. Will definitely include this in the next App Store build.

**Comment by KaffeDiem** [comment]
@Terabyte1385 been working a bit on the [settings overhaul](https://github.com/KaffeDiem/dIM/tree/feature/settings_overhaul) branch. I decided to remove the ability to revert your username after changing it, even though I was loving the feature, but it was introducing a lot of unnecessary complexity. Instead I added an alert when trying to confirm the changes. As you may see in the branch, quite a few things have been re-worked and this has taken a lot more time than expected. 
Will have the next couple of weeks off to finally get this out on the App Store. Thanks for your work! 

I realised that there were an old bug lying around. The private and public keys has to be regenerated as well when changing your username (and I did not want to save this when reverting the username)

If you have any additional suggestions for the settings page, please do let me know.

**Comment by KaffeDiem** [comment]
@Terabyte1385 
Currently in App Store review for public beta testing.

**Comment by Terabyte1385** [comment]
Awesome, very excited for this! First sort of major contribution to an App Store app! Keep me updated

**Comment by KaffeDiem** [comment]
@Terabyte1385 
Version 2.0.0 build 4 is [now available on TestFlight.](https://testflight.apple.com/join/8PkYfLzO) So far, this will be a release candidate. Will need to do proper testing as lots of things have changed with this build. Also a fifth build will probably need to be a bit of migration code for users using older versions of the app.

**Comment by KaffeDiem** [comment]
Closed this issue by accident

@Terabyte1385 version 2.0.0 build 9 is now in official App Store review process. 
See `tags` for the release candidate.

**Comment by KaffeDiem** [comment]
@Terabyte1385 the build has been approved. 
Will need to do a bit more testing tonight before I release it.

**Comment by KaffeDiem** [comment]
The re-designed settings page is live on the App Store. 
Thanks @Terabyte1385 !
