### ISSUE TITLE
Questions about mesh networking

### ISSUE THREAD

**Issue by kicks66** [KaffeDiem/dIM#33]
Hi there, I just came across your application and it looks amazing! I've been looking for something that provides this functionality, so this is very exciting. I had two questions I wanted to ask though:

1. for the mesh networking element, does the "repeating" of the message work even if the nearby user is not added as a friend?
2. how many times do messages get repeated?
3. does the repeating work even with different apps? i.e. the app store app and running the code here independently?

**Comment by KaffeDiem** [comment]
1. The repeating does very much work! The 'repeating' phone does not care who the message is from, or where it is going. It just concludes that the message it not meant for it, thus bouncing it on. 
2. Until all connected phones have seen it at least once. Each phone keep an array of previously seen messages. If a message has been seen before, it is not passed on again. 
3. Yes. The devices does not care where the message comes from, only that they are correctly formatted. This would make the protocol easy to implement also on Android or as a Mac application (which there currently is a working branch for, `Mac Catalyst`).

**Comment by kicks66** [comment]
Thanks for the answers KaffeDiem - these are exactly the answers I was hoping for!
