### ISSUE TITLE
Adding Simplified Chinese Translation

### ISSUE THREAD

**Issue by TheodoreEMatt** [KaffeDiem/dIM#36]
Hello @KaffeDiem 

I want to start by expressing my appreciation and admiration for this project. I am a developer from the People’s Republic of China, and I have recently forked your repository to **add a Simplified Chinese translation.**

In addition to the translation, **I have also made modifications to the software’s name and icons.** Please be aware of these changes.
Repository: [Link](https://github.com/TheodoreEMatt/CialloChat-By-dIM)
I wanted to inform you about this and discuss the next steps. Please let me know if there are any modifications or additional steps required to integrate these changes.

Thank you for your original work on this project. I look forward to your feedback.

**Best regards,**
Matt

**Comment by KaffeDiem** [comment]
Hi Matt! Feel free to update the name and icon, as long as the original license is respected I'm cool with anything 🤠  good work on the file uploading. Let me know if it's something you would consider merging into the original repository.

**Comment by TheodoreEMatt** [comment]
> Hi Matt! Feel free to update the name and icon, as long as the original license is respected I'm cool with anything 🤠  good work on the file uploading. Let me know if it's something you would consider merging into the original repository.

Dear KaffeDiem,

Thank you very much for your positive response and your openness to merging my changes into the repository. I am honored to contribute to this project. I genuinely appreciate and enjoy this software, so I will do my best to find time to translate it into Chinese. I am also very happy to use this software for small-scale entertainment in real life.😃

**However, I have a concern: I'm not sure if merging my fork will replace all the untranslated English parts of the software with Chinese, potentially leading to a complete Chinese version.**😢😢

My technical skills are still developing, and as a student in the People's Republic of China, I might not have many opportunities and time to extensively learn and modify the software. Such opportunities are quite rare for me.🥺

Could you please advise on this matter and suggest any solutions? Your guidance would be greatly appreciated.

**Thank you once again for your support.**🙏

**Best regards**,  
Matt
19/7/24 16:51（UTC+8）
