### ISSUE TITLE
Your website is offline

### ISSUE THREAD

**Issue by FellowTraveler** [KaffeDiem/dIM#37]
Domain expired. You should continue on this app because FireChat is apparently gone, there are no/few options available right now for mesh chat in disaster zones or other "network down/overloaded" scenarios.

**Comment by Terabyte1385** [comment]
> Domain expired. You should continue on this app because FireChat is apparently gone, there are no/few options available right now for mesh chat in disaster zones or other "network down/overloaded" scenarios.

Agreed. This project should continue. Understandably, it is time-consuming, and most of us, myself included, would be working on this in our free time.

As for the emergency comms, I don't think it's reliable enough for that, since everyone would need to have the app to make a reliable mesh network, but for chatting with friends or family in a plane while sitting in different rows would be a non-Armageddon, real, practical use case. Don't get me wrong, I love the lifeline idea. Regardless, I still believe this project has potential.

**Comment by KaffeDiem** [comment]
The feedback has been duly noted! It keeps surprising me that people are actually using dIM. I will look into renewing the domain (and App Store Developer subscription) 🥲

**Comment by KaffeDiem** [comment]
The domain has now been renewed. I suppose it takes a few hour before the website is completely back up. 
Thank you for letting me know!

**Comment by FellowTraveler** [comment]
well wait a second. If I suddenly find myself in a disaster zone, and every single person already has a computer with a wifi and bluetooth transceiver in their pocket with a built-in speaker and microphone plus camera and keyboard, it seems completely ridiculous in 2024 that those people would not have the ability to form a mesh network for their emergency communications. In fact, if I have the app on my phone, any person should be able to install the app FROM my phone TO their phone. In a disaster zone, why would this not be possible? The hardware can totally handle it. If we were talking about desktop computers, it would just be an accepted fact that we could give each other copies of applications and run them on our own devices. If we can't do that with the device in our pocket then that is a serious problem with that device. The only reason we wouldn't be able to do it is because the device specifically prevents us from doing so. I'm starting to wonder if I should even use such a device given just how ridiculous that is, that in 2024, when everyone has a tricorder in their pocket, they can't just form a mesh network for communications in a disaster zone, purely because the device disallows it....?

**Comment by FellowTraveler** [comment]
45% of total smartphone users apparently don't even have cell phone service.
There are also reasonable scenarios other than disaster zones.
For example, concerts. Festivals. Riots. Protests. Blackouts.

**Comment by Terabyte1385** [comment]
> well wait a second. If I suddenly find myself in a disaster zone, and every single person already has a computer with a wifi and bluetooth transceiver in their pocket with a built-in speaker and microphone plus camera and keyboard, it seems completely ridiculous in 2024 that those people would not have the ability to form a mesh network for their emergency communications. In fact, if I have the app on my phone, any person should be able to install the app FROM my phone TO their phone. In a disaster zone, why would this not be possible? The hardware can totally handle it. If we were talking about desktop computers, it would just be an accepted fact that we could give each other copies of applications and run them on our own devices. If we can't do that with the device in our pocket then that is a serious problem with that device. The only reason we wouldn't be able to do it is because the device specifically prevents us from doing so. I'm starting to wonder if I should even use such a device given just how ridiculous that is, that in 2024, when everyone has a tricorder in their pocket, they can't just form a mesh network for communications in a disaster zone, purely because the device disallows it....?

It's not as simple as that. First of all, not all devices are compatible with all other devices. There is no standard on what to do with messages received via Bluetooth. And even if there were, not all manufacturers adhere to it.
Secondly, the dIM is required on each device to form the mesh network because otherwise the devices have no idea what to do with the messages. dIM is the handler of these messages.

Most of the issues you're describing are OS limitations or other limitations out of dIM's control.

**Comment by Terabyte1385** [comment]
What could replace a bunch of users in cases like this are repeaters, but they're expensive to operate, maintain and not worth setting up in the first place in a world where there is no standard on what devices do with BLE messages.

**Comment by FellowTraveler** [comment]
What about when there is normal network connectivity? Does the app have an alternate "network available" mode? Or is it bluetooth mesh only?

**Comment by Terabyte1385** [comment]
> What about when there is normal network connectivity? Does the app have an alternate "network available" mode? Or is it bluetooth mesh only?

At the moment, no. All messages are sent via Bluetooth. We could, however, add messaging via Internet when there is an available connection.

**Comment by FellowTraveler** [comment]
It does form a mesh? or no? Meaning: if the recipient is out of range but there are other dim instances between us.

**Comment by Terabyte1385** [comment]
> It does form a mesh? or no? Meaning: if the recipient is out of range but there are other dim instances between us.

Yes, between dIM users. If you're A and you're trying to text C but you're not in C's range but B is, your message first goes to B which sends it to C on your behalf.

**Comment by KaffeDiem** [comment]
@Terabyte1385 is completely right here. 
@FellowTraveler a "network available"-mode would be so nice. This could bring dIM on par with something like Signal. I imagine that users could transfer files and videos over mobile networks, and simple text messages through Bluetooth. 
It is, however, extremely complex to handle. Not to mention all the added issues of introducing one (or more) servers.

**Comment by Terabyte1385** [comment]
Website is live, I think this issue can be closed.
